"""create_kb_tables

Revision ID: 9a2930672730
Revises:
Create Date: 2026-04-30 12:16:50.648028
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a2930672730"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kb_document",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("PDF", "DOCX", "HTML", "MARKDOWN", "TXT", "XLSX", name="kb_source_type", create_constraint=True),
            nullable=False,
        ),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("doc_type", sa.String(length=32), nullable=False),
        sa.Column("card_type", sa.String(length=32), nullable=True),
        sa.Column("customer_tier", sa.String(length=32), nullable=True),
        sa.Column("security_level", sa.String(length=16), nullable=False),
        sa.Column("version", sa.String(length=16), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "ARCHIVED",
                "KAFKA_PENDING",
                name="kb_doc_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("updated_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("kb_document", schema=None) as batch_op:
        batch_op.create_index("ix_kb_document_category", ["category"], unique=False)
        batch_op.create_index(
            "ix_kb_document_content_hash",
            ["content_hash"],
            unique=True,
            postgresql_where=sa.text("content_hash IS NOT NULL"),
        )
        batch_op.create_index("ix_kb_document_status", ["status"], unique=False)

    op.create_table(
        "kb_chunk",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("document_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column(
            "embedding_status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", name="kb_embed_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("es_indexed", sa.Boolean(), nullable=False),
        sa.Column("milvus_indexed", sa.Boolean(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["kb_document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("kb_chunk", schema=None) as batch_op:
        batch_op.create_index("ix_kb_chunk_doc_index", ["document_id", "chunk_index"], unique=False)
        batch_op.create_index(batch_op.f("ix_kb_chunk_document_id"), ["document_id"], unique=False)
        batch_op.create_index(
            "ix_kb_chunk_embedding_status",
            ["embedding_status"],
            unique=False,
            postgresql_where=sa.text("embedding_status = 'PENDING'"),
        )
        batch_op.create_index(
            "ix_kb_chunk_es_indexed", ["es_indexed"], unique=False, postgresql_where=sa.text("es_indexed = false")
        )
        batch_op.create_index(
            "ix_kb_chunk_milvus_indexed",
            ["milvus_indexed"],
            unique=False,
            postgresql_where=sa.text("milvus_indexed = false"),
        )

    op.create_table(
        "kb_ingestion_log",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("document_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "PARSE",
                "CLEAN",
                "CHUNK",
                "EMBED",
                "ES_WRITE",
                "MILVUS_WRITE",
                "KAFKA_PUBLISH",
                name="kb_ingestion_stage",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "SUCCESS", "FAILED", name="kb_ingestion_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("step_detail_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["kb_document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("kb_ingestion_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kb_ingestion_log_document_id"), ["document_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kb_ingestion_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kb_ingestion_log_document_id"))

    op.drop_table("kb_ingestion_log")
    with op.batch_alter_table("kb_chunk", schema=None) as batch_op:
        batch_op.drop_index("ix_kb_chunk_milvus_indexed", postgresql_where=sa.text("milvus_indexed = false"))
        batch_op.drop_index("ix_kb_chunk_es_indexed", postgresql_where=sa.text("es_indexed = false"))
        batch_op.drop_index("ix_kb_chunk_embedding_status", postgresql_where=sa.text("embedding_status = 'PENDING'"))
        batch_op.drop_index(batch_op.f("ix_kb_chunk_document_id"))
        batch_op.drop_index("ix_kb_chunk_doc_index")

    op.drop_table("kb_chunk")
    with op.batch_alter_table("kb_document", schema=None) as batch_op:
        batch_op.drop_index("ix_kb_document_status")
        batch_op.drop_index("ix_kb_document_content_hash", postgresql_where=sa.text("content_hash IS NOT NULL"))
        batch_op.drop_index("ix_kb_document_category")

    op.drop_table("kb_document")
    # ### end Alembic commands ###
